### ISSUE TITLE
Migration of plugin.yml content to build script

### ISSUE THREAD

**Issue by osipxd** [EndlessCodeGroup/BukkitGradle#69]
It would be great to generate a snippet to migrate content of `plugin.yml` to a build script. It would be useful both, for new users who wants to migrate and for the existing, who had been using the plugin before v1.0.0 (are there anybody? :D)

For example, if a user has the following `plugin.yml`:

```yaml
api-version: 1.21.5
name: MyPlugin
version: '1.0'
main: org.example.myplugin.MyPlugin
depend: [Vault]
commands:
  myplugin:
    description: Print info anout the plugin
```

the following message should be shown in build log:

```
Some of the 'plugin.yml' properties are not generated from a build script.
Consider moving them into the build script and removing the 'plugin.yml' file.
Add these lines to the build script:

bukkit {
    apiVersion = "1.21.5"

    plugin {
        name = "MyPlugin"
        version = "1.0"
        main = "org.example.myplugin.MyPlugin"
        depend = listOf("Vault")
        commands {
            register("myplugin") {
                description = "Print info anout the plugin"
            }
        }
    }
}
```
